language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t pxinghao/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pxinghao/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket-name: "elasticbeanstalk-ap-southeast-1-943926308797"
  bucket-path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  